stages:
  - test
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# JOB 1 : Lancer les tests unitaires
test:
  stage: test
  tags:
    - vm1
  image: maven:3.9-eclipse-temurin-17
  script:
    - mkdir -p ~/.m2
    - |
      cat > ~/.m2/settings.xml << EOF
      <settings>
        <mirrors>
          <mirror>
            <id>maven-default-http-blocker</id>
            <mirrorOf>dummy</mirrorOf>
            <url>http://0.0.0.0/</url>
            <blocked>false</blocked>
          </mirror>
        </mirrors>
        <servers>
          <server>
            <id>nexus-releases</id>
            <username>admin</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
          <server>
            <id>nexus-snapshots</id>
            <username>admin</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
        </servers>
      </settings>
      EOF
    - mvn test
  cache:
    paths:
      - .m2/repository

# JOB 2 : Compiler le projet et générer le JAR
build:
  stage: build
  tags:
    - vm1
  image: maven:3.9-eclipse-temurin-17
  script:
    - mkdir -p ~/.m2
    - |
      cat > ~/.m2/settings.xml << EOF
      <settings>
        <mirrors>
          <mirror>
            <id>maven-default-http-blocker</id>
            <mirrorOf>dummy</mirrorOf>
            <url>http://0.0.0.0/</url>
            <blocked>false</blocked>
          </mirror>
        </mirrors>
        <servers>
          <server>
            <id>nexus-releases</id>
            <username>admin</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
          <server>
            <id>nexus-snapshots</id>
            <username>admin</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
        </servers>
      </settings>
      EOF
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  cache:
    paths:
      - .m2/repository

# JOB 3 : Construire l'image Docker et la pousser sur Docker Hub
docker:
  stage: docker
  tags:
    - vm1
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  dependencies:
    - build

# Ce pipeline se déclenche uniquement sur la branche develop
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
