apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: devops-l3gl
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "root"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: munikmind/product-api:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 100
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 100
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "400m"
              memory: "768Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: devops-l3gl
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30086
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress
  namespace: devops-l3gl
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-api-service
                port:
                  number: 8086
